version: "3.7"

services:
  web:
    build: .
    command: php -S 0.0.0.0:8040 -t src/
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 8040:80
    networks:
      - host

networks:
  host:

  